steps:
  - name: 'hashicorp/terraform:1.6.3'
    args: ['init']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['plan', '-out=tfplan']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['apply', 'tfplan']
    env:
    - "TF_STATE_OUT=cloudbuild.tfstate"
