steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/mukeshbhoir/vpc_creation.git']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['init']
    #     '-backend-config=project=${PROJECT_ID}',
    # '-backend-config=bucket=mukeshbhoir199222']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['plan', '-out=tfplan']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['destroy']
    env:
    - "TF_STATE_OUT=cloudbuild.tfstate"
