steps:
  - name: 'hashicorp/terraform:1.0.0'
  args: ['init',
    '-backend-config=project=${PROJECT_ID}',
    '-backend-config=bucket=${_BUCKET}']
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
  - name: 'hashicorp/terraform:1.0.0' 
  args: ['plan']
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
  - name: 'hashicorp/terraform:1.0.0'
  args: ['apply']
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
substitutions:
    _BUCKET: terraformbuckettest
tags: ['cloud-builders-community']
