steps:
  - name: 'hashicorp/terraform:1.6.3'
    args: ['init',
     '-backend-config=project=${PROJECT_ID}',
     '-backend-config=bucket=mukeshbhoir199222']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['plan', '-out=tfplan']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['apply', 'tfplan']
    env:
    - "TF_STATE_OUT=cloudbuild.tfstate"
