steps:
  - name: 'hashicorp/terraform:1.6.3'
    args: ['init']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['fmt']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['reset']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['plan', '-out=tfplan']
  - name: 'hashicorp/terraform:1.6.3'
    args: ['destroy']
    env:
    - "TF_STATE_OUT=cloudbuild.tfstate"
